mklink    "%USERPROFILE%/.vimrc"                           "%USERPROFILE%\Dropbox\dotfiles\.vimrc"
mklink    "%USERPROFILE%/.gvimrc"                          "%USERPROFILE%\Dropbox\dotfiles\.gvimrc"
mklink    "%USERPROFILE%/.vimshrc"                         "%USERPROFILE%\Dropbox\dotfiles\.vimshrc"
mklink    "%USERPROFILE%/.vimperatorrc"                    "%USERPROFILE%\Dropbox\dotfiles\.vimperatorrc"
mklink /d "%USERPROFILE%/vimfiles"                         "%USERPROFILE%\Dropbox\dotfiles\.vim"
mklink /d "%USERPROFILE%/vimperator"                       "%USERPROFILE%\Dropbox\dotfiles\.vimperator"
mklink    "%USERPROFILE%/.minttyrc"                        "%USERPROFILE%\Dropbox\dotfiles\.minttyrc"
mklink    "%USERPROFILE%/AppData/Roaming/keyhac/config.py" "%USERPROFILE%\Dropbox\dotfiles\config.py"
